import { getStore, replaceState, snapshot } from "../store";
import {
  clearStorage,
  defaultState,
  exportFilename,
  mergeImport,
  validateImport,
  uid as newId,
} from "../state";
import { esc, html, raw, confirmAction } from "../ui/components";
import type { MealSlot } from "../types";
import { currentUser, signOut as authSignOut } from "../firebase/auth";
// Bundled at build time so the in-app prompt and the repo doc never drift.
import importPrompt from "../../IMPORT.md?raw";

export function openSettings(dialog: HTMLDialogElement, onChange: () => void): void {
  render(dialog, onChange);
  if (!dialog.open) dialog.showModal();

  // Close on backdrop click. Re-bound each open to match the current article.
  dialog.addEventListener(
    "click",
    (e) => {
      const article = dialog.querySelector("article");
      if (!article) return;
      const rect = (article as HTMLElement).getBoundingClientRect();
      const inside =
        e.clientX >= rect.left &&
        e.clientX <= rect.right &&
        e.clientY >= rect.top &&
        e.clientY <= rect.bottom;
      if (!inside) dialog.close();
    },
    { once: true },
  );
}

function render(dialog: HTMLDialogElement, onChange: () => void): void {
  const store = getStore();
  const user = currentUser();

  dialog.innerHTML = html`
    <article>
      <header>
        <button aria-label="Close" rel="prev" id="settings-close"></button>
        <h3>Settings</h3>
      </header>

      ${raw(user ? renderAccountSection(user.email ?? "", store.profile.displayName) : "")}

      <h4>Daily targets</h4>
      <div class="row">
        <label class="grow">kcal
          <input id="set-kcal" type="number" min="0" step="50" value="${store.targets.kcal}" />
        </label>
        <label class="grow">protein (g)
          <input id="set-protein" type="number" min="0" step="5" value="${store.targets.protein}" />
        </label>
      </div>

      <h4>Meal slots</h4>
      <p class="muted"><small>The rows on your week grid. Add as many as you want (Breakfast, Snack, Pre-workout, etc.). Deleting a slot also clears any meals assigned to it.</small></p>
      ${raw(renderSlots(store.slots))}
      <div class="row">
        <input id="new-slot-label" placeholder="e.g. Breakfast" class="grow" />
        <button id="add-slot" class="outline">+ Add slot</button>
      </div>

      <h4>Backup</h4>
      <div class="row">
        <button id="export-btn">Export JSON</button>
      </div>
      <p class="muted"><small>${user ? "Your data also syncs automatically to your account — export is a manual backup on top of that." : "Drop the exported file in iCloud/Drive for a manual cross-device backup. Sign in to enable automatic cross-device sync."}</small></p>

      <h4>Import ingredients & meals</h4>
      <p class="muted"><small>Bulk-add ingredients and meals from a JSON file (e.g. one generated by a chat — see <strong>Copy import prompt</strong> below). Your slots, week plan, targets and shared items are untouched. Use the <strong>Share</strong> tab to move week plans between accounts.</small></p>
      <div class="row">
        <button id="import-btn" class="outline">Import JSON…</button>
        <input id="import-file" type="file" accept="application/json,.json" hidden />
        <button id="copy-prompt-btn" class="outline">Copy import prompt</button>
      </div>

      <h4>Reset</h4>
      <button id="reset-btn" class="outline secondary">Reset all data</button>
      ${raw("")}
    </article>
  `;

  wire(dialog, onChange);
}

function renderAccountSection(email: string, displayName: string): string {
  return `
    <h4>Account</h4>
    <p class="muted"><small>Signed in as <strong>${esc(email)}</strong></small></p>
    <label>Display name
      <input id="set-display-name" placeholder="(shown on items you share)" value="${esc(displayName)}" />
    </label>
    <button id="sign-out-btn" class="outline secondary">Sign out</button>
  `;
}

function renderSlots(slots: MealSlot[]): string {
  if (slots.length === 0) {
    return `<p class="muted"><small>No slots yet — add one below.</small></p>`;
  }
  return `<ul class="slot-list">${slots
    .map(
      (s, i) => `<li class="slot-row" data-slot-id="${esc(s.id)}">
        <input class="slot-label" data-idx="${i}" value="${esc(s.label)}" />
        <button class="outline" data-up="${i}" ${i === 0 ? "disabled" : ""} aria-label="Move up">↑</button>
        <button class="outline" data-down="${i}" ${i === slots.length - 1 ? "disabled" : ""} aria-label="Move down">↓</button>
        <button class="outline secondary" data-rm="${i}" aria-label="Remove slot">×</button>
      </li>`,
    )
    .join("")}</ul>`;
}

function wire(dialog: HTMLDialogElement, onChange: () => void): void {
  const store = getStore();

  const rerender = () => {
    render(dialog, onChange);
    onChange();
  };

  dialog.querySelector("#settings-close")?.addEventListener("click", () => dialog.close());

  (dialog.querySelector("#set-kcal") as HTMLInputElement).addEventListener("change", (e) => {
    store.targets.kcal = Math.max(0, Number((e.target as HTMLInputElement).value) || 0);
    onChange();
  });
  (dialog.querySelector("#set-protein") as HTMLInputElement).addEventListener("change", (e) => {
    store.targets.protein = Math.max(0, Number((e.target as HTMLInputElement).value) || 0);
    onChange();
  });

  // Display name
  dialog.querySelector("#set-display-name")?.addEventListener("change", (e) => {
    store.profile.displayName = (e.target as HTMLInputElement).value.trim();
  });

  // Sign out
  dialog.querySelector("#sign-out-btn")?.addEventListener("click", async () => {
    if (!confirmAction("Sign out? Your local data will stay on this device but won't sync until you sign in again.")) return;
    await authSignOut();
    dialog.close();
  });

  // Slot label change
  dialog.querySelectorAll<HTMLInputElement>("input.slot-label").forEach((el) => {
    el.addEventListener("change", () => {
      const idx = Number(el.dataset.idx);
      const label = el.value.trim();
      if (!label) {
        el.value = store.slots[idx].label;
        return;
      }
      store.slots[idx].label = label;
      rerender();
    });
  });

  // Reorder slots
  dialog.querySelectorAll<HTMLElement>("[data-up]").forEach((el) => {
    el.addEventListener("click", () => {
      const i = Number(el.dataset.up);
      if (i <= 0) return;
      const arr = [...store.slots];
      [arr[i - 1], arr[i]] = [arr[i], arr[i - 1]];
      store.slots = arr;
      rerender();
    });
  });
  dialog.querySelectorAll<HTMLElement>("[data-down]").forEach((el) => {
    el.addEventListener("click", () => {
      const i = Number(el.dataset.down);
      const arr = [...store.slots];
      if (i >= arr.length - 1) return;
      [arr[i], arr[i + 1]] = [arr[i + 1], arr[i]];
      store.slots = arr;
      rerender();
    });
  });

  // Remove slot — also strip its key from every day in the week plan.
  dialog.querySelectorAll<HTMLElement>("[data-rm]").forEach((el) => {
    el.addEventListener("click", () => {
      const i = Number(el.dataset.rm);
      const slot = store.slots[i];
      if (!slot) return;
      if (!confirmAction(`Remove "${slot.label}" slot? Meals assigned to it across the week will be unassigned.`)) return;
      store.slots = store.slots.filter((_, idx) => idx !== i);
      for (const day of Object.keys(store.week) as (keyof typeof store.week)[]) {
        delete store.week[day][slot.id];
      }
      rerender();
    });
  });

  // Add slot
  dialog.querySelector("#add-slot")?.addEventListener("click", () => {
    const input = dialog.querySelector("#new-slot-label") as HTMLInputElement;
    const label = input.value.trim();
    if (!label) {
      input.focus();
      return;
    }
    const id = newId();
    store.slots = [...store.slots, { id, label }];
    for (const day of Object.keys(store.week) as (keyof typeof store.week)[]) {
      store.week[day][id] = null;
    }
    input.value = "";
    rerender();
  });
  dialog.querySelector("#new-slot-label")?.addEventListener("keydown", (e) => {
    if ((e as KeyboardEvent).key === "Enter") {
      e.preventDefault();
      (dialog.querySelector("#add-slot") as HTMLButtonElement).click();
    }
  });

  dialog.querySelector("#export-btn")?.addEventListener("click", () => {
    const json = JSON.stringify(snapshot(store), null, 2);
    const blob = new Blob([json], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = exportFilename();
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  });

  const fileInput = dialog.querySelector("#import-file") as HTMLInputElement;
  dialog.querySelector("#import-btn")?.addEventListener("click", () => fileInput.click());
  fileInput.addEventListener("change", async () => {
    const file = fileInput.files?.[0];
    if (!file) return;
    try {
      const text = await file.text();
      const parsed = JSON.parse(text);
      const payload = validateImport(parsed);
      if (!payload) {
        alert("That file doesn't look like a valid ingredients/meals JSON.");
        return;
      }
      const ingN = payload.ingredients.length;
      const mealN = payload.meals.length;
      const summary = `Add ${ingN} ingredient${ingN === 1 ? "" : "s"} and ${mealN} meal${mealN === 1 ? "" : "s"} to your library? Your week plan and slots are untouched.`;
      if (!confirmAction(summary)) return;
      mergeImport(store, payload);
      onChange();
      dialog.close();
    } catch (err) {
      alert("Couldn't read that file: " + (err instanceof Error ? err.message : String(err)));
    } finally {
      fileInput.value = "";
    }
  });

  dialog.querySelector("#copy-prompt-btn")?.addEventListener("click", async () => {
    try {
      await navigator.clipboard.writeText(importPrompt);
      alert("Import prompt copied to clipboard.");
    } catch {
      window.prompt("Copy the import prompt:", importPrompt);
    }
  });

  dialog.querySelector("#reset-btn")?.addEventListener("click", () => {
    if (!confirmAction("Delete all ingredients, meals, and the week plan? This can't be undone.")) return;
    clearStorage();
    replaceState(defaultState());
    onChange();
    dialog.close();
  });
}

export { esc };
